This code is for two agent system involving one UAV and one Rover starting from a same starting point. 

In [2]:
import numpy as np
import pandas as pd

task_dist=[10,40,20,20,10,50,20,30,10,10,20]
task_dist_GR1=np.array([10,40,20,20,10,50,20,30,10,10,20])
#task_dist_GR2= task_dist_GR1[::-1]
task_dist_UAV1=np.array([70,0,0,0,100,0,40,0,110,110,0])
#task_dist_UAV2=task_dist_UAV1[::-1]
alt=[1600,1800]
#print(task_dist_GR2)
tasks= len(task_dist)
k1=np.array( [1,0,0,0,1,0,1,0,1,1,0]) #capability matrix defines if the tasks defined can be completed by the UAVs or not
k2= np.array(np.ones(11)) #capability matrix defines if the tasks defined can be completed by the GRs or not
slope_LR=(np.array([1.5, -3, 3,4,-3,-2,1,3,-2,2,-3]))
#print(slope_LR)
slope_RL= slope_LR *-1
#print(slope_RL)

task_dist_f= np.c_[task_dist_GR1, task_dist_UAV1]
#print(task_dist_f)
#task_dist_d= pd.DataFrame[{'GR1':task_dist_GR1,'UAV1':task_dist_UAV1}]
#print(task_dist_d)

slope_LR_f=[]
for i in slope_LR:
  slope=i
  #print(slope)
  if(slope<0):
    slope= ((slope*-1)/10)
    slope_LR_f.append(slope)
  elif (slope>0):
    slope_LR_f.append(slope)
  else:
    slope=1
    slope_LR_f.append(slope)

#print(slope_LR_f)
## AUCTION BID CALCULATION 
j=1
#print(j)
bid= np.zeros((11,2))
for i in range(len(task_dist_f)):
  for j in range(len(task_dist_f[i])):
    if (j==1):  
      bid[i][j]= slope_LR_f[i]*task_dist_f[i][j]
      j=j+1   
    else:
      bid[i][j]= task_dist_f[i][j]*10
print("Bids collected by two agents are as follows:")
print(bid)

## Best Bid Slection
m=0
i=0
j=0
best_bid=np.zeros(11)
task_agent=[]
#print(best_bid)
for m in range(len(bid)):
    i=0
    #print(m)
    #print(bid[m])
    l1=bid[m]
    l1=np.sort(l1)
    #print(l1)
    x=l1[i]
    #print(x)
    best_bid[m]=x
    task_agent[m]=""
    if (x==0):
        x=l1[i+1]
        best_bid[m]=x
        #print(best_bid[m])
print("best bids for the tasks are as follows:")
print(best_bid)
    

 

Bids collected by two agents are as follows:
[[100. 105.]
 [400.   0.]
 [200.   0.]
 [200.   0.]
 [100.  30.]
 [500.   0.]
 [200.  40.]
 [300.   0.]
 [100.  22.]
 [100. 220.]
 [200.   0.]]
best bids for the tasks are as follows:
[100. 400. 200. 200.  30. 500.  40. 300.  22. 100. 200.]


Possible loopholes and solutions:

1. **I have considered that both robots have the same starting point**. For us to consider multiple starting positions, we need to come up with a coordinate system with a sign convention (in my opinion), where moving left should be negative and moving right will be positive.

2. **When considering different starting location, there has to be a traveral cost for reaching the task point**, so the bid should involve (traversal+task cost).

3. **UAV take-off cost aren't considered**.



In [5]:
import numpy as np
import pandas as pd

task_dist=[10,40,60,20,50,20,30,10,10,20]
task_dist_GR1=np.array([10,40,60,20,50,20,30,10,10,20])
#task_dist_GR2= task_dist_GR1[::-1]
task_dist_UAV1=np.array([70,0,0,100,0,40,0,110,110,0])
#task_dist_UAV2=task_dist_UAV1[::-1]
alt=[1600,1800]
#print(task_dist_GR2)
tasks= len(task_dist)
k1=np.array( [1,0,0,0,1,0,1,0,1,1,0]) #capability matrix defines if the tasks defined can be completed by the UAVs or not
k2= np.array(np.ones(11)) #capability matrix defines if the tasks defined can be completed by the GRs or not
slope_LR=(np.array([1.5, -3, 3,-3,-2,1,3,-2,2,-3]))
#print(slope_LR)
slope_RL= slope_LR *-1
#print(slope_RL)

task_dist_f= np.c_[task_dist_GR1, task_dist_UAV1]
#print(task_dist_f)
#task_dist_d= pd.DataFrame[{'GR1':task_dist_GR1,'UAV1':task_dist_UAV1}]
#print(task_dist_d)

slope_LR_f=[]
for i in slope_LR:
  slope=i
  #print(slope)
  if(slope<0):
    slope= ((slope*-1)/10)
    slope_LR_f.append(slope)
  elif (slope>0):
    slope_LR_f.append(slope)
  else:
    slope=1
    slope_LR_f.append(slope)

#print(slope_LR_f)
## AUCTION BID CALCULATION 
j=1
#print(j)
bid= np.zeros((10,2))
bid_agent=["GR1","UAV1"] 
for i in range(len(task_dist_f)):
  for j in range(len(task_dist_f[i])):
    if (j==1):  
      bid[i][j]= slope_LR_f[i]*task_dist_f[i][j]
      j=j+1   
    else:
      bid[i][j]= task_dist_f[i][j]*10
print("Bids collected by two agents are as follows:")
print(bid)

## Best Bid Slection
m=0
i=0
j=0
best_bid=np.zeros(10)
task_agent=[]
#print(best_bid)
for m in range(len(bid)):
    i=0
    #print(m)
    #print(bid[m])
    l1=bid[m]
    l2=np.sort(l1)
    Z = [bid_agent for _,bid_agent in sorted(zip(l1,bid_agent))]
    #print(Z)
    #print(l1)
    x=l2[i]
    #print(x)
    
    if (x==0):
        x=l2[i+1]
        best_bid[m]=x
        agent=Z[i+1]
        task_agent.insert(m,agent)
    else:
        best_bid[m]=x
        agent=Z[i]
        #print(agent)
        task_agent.insert(m,agent)
        
        
        #print(best_bid[m])
print("best bids for the tasks are as follows:")
print(best_bid)

print("Task allocation")
print(task_agent)



Bids collected by two agents are as follows:
[[100. 105.]
 [400.   0.]
 [600.   0.]
 [200.  30.]
 [500.   0.]
 [200.  40.]
 [300.   0.]
 [100.  22.]
 [100. 220.]
 [200.   0.]]
best bids for the tasks are as follows:
[100. 400. 600.  30. 500.  40. 300.  22. 100. 200.]
Task allocation
['GR1', 'GR1', 'GR1', 'UAV1', 'GR1', 'UAV1', 'GR1', 'UAV1', 'GR1', 'GR1']


The code below attempts to solve the overlap problem

In [11]:
import numpy as np
import pandas as pd

trip_distance=[70,100,110,110,40]
trip_coord=[[0,70],[60,160],[90,200],[110,230],[110,150]]
overlap= np.zeros((5,5))

for i in range(len(trip_coord)-1):
    min_coord=trip_coord[i][0]
    max_coord=trip_coord[i][1]
    min_next=trip_coord[i+1][0]
    max_next=trip_coord[i+1][1]
    overlap[i][i]=0
    overlap[i][i+1]= max(0,min(max_coord,max_next)-max(min_coord,min_next))
    
print(overlap)

[[ 0. 10.  0.  0.  0.]
 [ 0.  0. 70.  0.  0.]
 [ 0.  0.  0. 90.  0.]
 [ 0.  0.  0.  0. 40.]
 [ 0.  0.  0.  0.  0.]]


UAV coordination

In [42]:
import numpy as np
import pandas as pd

trip_distance=[120,100,140,90,180,90]
trip_cord=[[0,120],[0,100],[70,210],[90,180],[30,210],[120,210]]
y=1800
uav1=0
uav2=210
d1=0
d2=0
allocated_agent=[]
op_cost=np.zeros(2)
total_cost=0
j=0
for i in range(len(trip_cord)):
    
    x1=trip_cord[i][0]
    x2=trip_cord[i][1]
    if x1 <= uav1 <= x2:
        allocated_agent.insert(i,"UAV1")
    elif x1 <= uav2 <= x2:
        allocated_agent.insert(i,"UAV2")
    else:
        allocated_agent.insert(i,"NA")
        
    
        
print("Allocated agents are:")
print(allocated_agent)
print("\nTotal cost of operation:")
print(total_cost)


Allocated agents are:
['UAV1', 'UAV1', 'UAV2', 'NA', 'UAV2', 'UAV2']

Total cost of operation:
0
